[client]
toolbarMode = "minimal" 
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#0757B8"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#0F1115"
font = "sans serif"
